name: mudblazor-ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/templates.csproj
    - name: Build
      run: dotnet build ./src/templates.csproj --no-restore
    - name: Test
      run: dotnet test ./src/templates.csproj --no-build --verbosity normal
      
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.BOT_AUTO_APPROVE }}"
